### ISSUE TITLE
error function not defined

### ISSUE THREAD

**Issue by pushkin-** [nilbus/Backbone.dualStorage#148] opened 2015-08-07 18:06 UTC
relayErrorCallback = function(xhr) {
       var online;
       online = !hasOfflineStatusCode(xhr);
       if (online || method === 'read' && !options.storeExists) {
         return error(xhr);
       } else {
         return useOfflineStorage();
       }
     };

It appears that `error` is not defined anywhere.

**Comment by nilbus** [comment] 2015-08-12 09:43
`error` is defined in the closure of the dualsync function, where it is defined. It refers to the error callback passed in to `Backbone.sync` (after being translated to support multiple Backbone versions).

https://github.com/nilbus/Backbone.dualStorage/blob/1528f32441339e93f1a6fc9d70bb3587fa594e7f/backbone.dualstorage.js#L348

Did this cause you an error, or were you analyzing the code?

**Comment by pushkin-** [comment] 2015-08-12 16:03
@nilbus Hmm. It caused me an error.

**Comment by nilbus** [comment] 2015-08-12 16:49
Are you on Backbone 0.9.10? Assuming not…

If `error` was undefined, that means that `dualsync` (`Backbone.sync`) was called with an undefined options.error callback. That should be impossible with a vanilla version of backbone, which always calls `wrapError` to define `options.error` (see http://backbonejs.org/docs/backbone.html).

Let me know if you figure out what's happening here.

**Comment by pushkin-** [comment] 2015-08-12 22:28
No I don't believe I am using Backbone 0.9.10.

My internship ended, so I don't have access to my code anymore, and replicating it will be difficult. However, I will let you know if I figure something out.

**Comment by nilbus** [comment] 2015-08-13 00:40
Okay. Sorry I couldn't get to this sooner then! I'll close this since we can't reproduce it now, but it will be here for someone to find if they run into the same problem.

Thanks for all your help reporting issues :) :clap:

**Closed by nilbus** 2015-08-13 00:40 UTC
